version: '4'

services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-ms
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: product-service

volumes:
  mongodb-data:
